Fix synthesizer object
TomonobuHayakawa/spresense pull request #8
Opened 2019-09-03 09:57 UTC by ShinjiShinozaki

@TomonobuHayakawa さん
途中ですがPullReqします。
よろしくお願いいたします。

2019-09-03 10:05 UTC, RyuutaSakane commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +static OscillatorComponent    *s_cmp_obj = NULL;
クラスメンバにした方がいいです。

2019-09-03 10:05 UTC, RyuutaSakane commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +  s_cmp_obj = new OscillatorComponent(s_msgq_id.dsp, s_pool_id.dsp);
newはせずに、クラスメンバとして保持しておき、Componentを切り替える必要があるなら、ポインタだけを切り替えるようにしましょう。

2019-09-03 10:05 UTC, RyuutaSakane commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +      delete s_cmp_obj;
new, deleteはしない設計で。

2019-09-03 10:15 UTC, RyuutaSakane commented
componentに明示的にstateを持たせた設計にしましょう。ReadyとActiveだけで行けると思います。
動くレベルになったら共通化できる部分はベースクラスに出して、他のComponentも揃えたいですね。

2019-09-05 07:23 UTC, TomonobuHayakawa commented on sdk/configs/examples/audio_oscillator-defconfig
> +CONFIG_AUDIOUTILS_PLAYER=y
Playerは変なので、ちゃんと追加すべき。

2019-09-05 07:25 UTC, TomonobuHayakawa commented on sdk/modules/audio/components/oscillator/Make.defs
CONFIG_AUDIOUTILS_OSCILLATORではなく、SYNTHESIZER

2019-09-05 07:26 UTC, TomonobuHayakawa commented on sdk/modules/audio/components/oscillator/oscillator_component.cpp
>            p_inst->recv(p_response);
Decも変です。

2019-09-05 07:28 UTC, TomonobuHayakawa commented on sdk/modules/audio/components/oscillator/oscillator_component.cpp
> +  m_instance = param.instance;
なんのinstance?　クラスの？

2019-09-05 07:32 UTC, TomonobuHayakawa commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +      s_cmp_obj = new OscillatorComponent(s_msgq_id.dsp, s_pool_id.dsp);
Actコマンドの中でnewしちゃだめ。
newしたものを付け替える。
フラグメンテーションする。

2019-09-05 07:35 UTC, TomonobuHayakawa commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +  uint32_t  max_pcm_buff_size = 768 * 2 * 2;
これ暫定？
数字もそうだけど、ローカル変数にする理由は？
スタックあふれるのでは？

2019-09-05 07:37 UTC, TomonobuHayakawa commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.h
> +
Segmentの数による。何か依存をつけられないのかな？

2019-09-05 09:09 UTC, ShinjiShinozaki commented on sdk/modules/audio/components/oscillator/oscillator_component.cpp
> +  m_instance = param.instance;
initコマンドで設定するコールバックの引数に与えるパラメータとして用意しました。
コールバックにインスタンスがあると便利ですので追加しました。
この場合synthesizer_objクラスのインスタンスを設定しようと考えています。

2019-09-05 09:11 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +  uint32_t  max_pcm_buff_size = 768 * 2 * 2;
動くかどうか確認のための暫定コードです。すみません。
メッセージプールから計算するようにします。

2019-09-06 01:30 UTC, ShinjiShinozaki commented on sdk/modules/audio/components/oscillator/oscillator_component.cpp
>            p_inst->recv(p_response);
こちらはなぜかDecModeが返ってきていたので暫定でDecModeにしていました。
調査します。

2019-09-06 02:41 UTC, ShinjiShinozaki commented
途中ですが、
config周りについて修正しました。
よろしくお願いいたします。

2019-09-06 05:43 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +static OscillatorComponent    *s_cmp_obj = NULL;
メンバーに追加しました。

2019-09-06 05:44 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +  s_cmp_obj = new OscillatorComponent(s_msgq_id.dsp, s_pool_id.dsp);
new, delete の箇所を削除しました。
クラスのメンバーとしてアクセスするようにしました。

2019-09-06 05:44 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +      delete s_cmp_obj;
修正しました。

2019-09-06 05:45 UTC, ShinjiShinozaki commented on sdk/configs/examples/audio_oscillator-defconfig
> +CONFIG_AUDIOUTILS_PLAYER=y
AUDIOUTILS_SYNTHESIZERで、必要なモジュールをまとめました。

2019-09-06 05:45 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +      s_cmp_obj = new OscillatorComponent(s_msgq_id.dsp, s_pool_id.dsp);
修正しました。

2019-09-06 05:46 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.h
> +
poolのセグメントから計算できそうです。

2019-09-06 05:46 UTC, ShinjiShinozaki commented
途中ですが、new、deleteを使わない修正を行いました。
よろしくお願いいたします。

2019-09-06 07:05 UTC, ShinjiShinozaki commented
#define  MAX_OUT_BUFF_NUM  10  /* Number of PCM buffer. */
こちらの件を除いて修正しました。
よろしくお願いいたします。

2019-09-09 17:56 UTC, TomonobuHayakawa commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.h
> +
じゃあ、これは、別途検討。

2019-09-10 00:57 UTC, TomonobuHayakawa requested changes

2019-09-10 00:57 UTC, TomonobuHayakawa commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  init.bit_width  = 3;
3って何？ってなっちゃう。

2019-09-10 00:57 UTC, TomonobuHayakawa commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  init.channel_no = 2;
channel_numにしておいて。

2019-09-10 00:57 UTC, TomonobuHayakawa commented on sdk/modules/audio/components/oscillator/oscillator_component.cpp
> +  m_instance = param.instance;
別途会話。

2019-09-10 00:57 UTC, TomonobuHayakawa commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +#include "dsp_driver/include/dsp_drv.h"
これ要る？
compに隠せないの？DSP。

2019-09-10 01:07 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +#include "dsp_driver/include/dsp_drv.h"
DSPからの応答があった時のコールバックの引数がDspDrvComPrm_t構造体だったのでincludeしていました。
コールバックの引数を修正します。

2019-09-10 07:54 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +#include "dsp_driver/include/dsp_drv.h"
修正しました。OscComplParamにDSPからの情報を入れてコールバックで返すようにしました
。メンバーのinit_osc_paramはコールバックに乗らないので削除しました。

2019-09-10 07:56 UTC, ShinjiShinozaki commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  init.channel_no = 2;
修正しました。
また、frequencyをsampling_rateに修正しました。

2019-09-10 07:57 UTC, ShinjiShinozaki commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  init.bit_width  = 3;
AS_BITLENGTH_XXを使うようにして、synthesizer側でDSP値に変換するよう修正しました。

2019-09-10 07:59 UTC, ShinjiShinozaki commented
@TomonobuHayakawa さん
修正しました。
Set関数も入れました。
レビューお願いいたします。

2019-09-10 12:21 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +    }
３回オシレータにPCMデータを要求

2019-09-10 12:23 UTC, ShinjiShinozaki commented
@TomonobuHayakawa さん
３回オシレータの要求を出した後にミキサーに要求を出すよう修正しました。
よろしくお願いいたします。

2019-09-10 12:24 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +    }
3個PCMデータがたまったらミキサーへ要求し、ステートをExecuteし変更する

2019-09-10 18:39 UTC, TomonobuHayakawa commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  set_param.frequency  = 523;
ちなみに、523って何？

2019-09-10 18:39 UTC, TomonobuHayakawa commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  set_param.frequency  = 523;
同じにしたら、わけわかんない。

2019-09-10 18:48 UTC, TomonobuHayakawa commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +    }
そもそも暫定だよ。この処理。
PlayerのPreDecと同じ処理をするべき。

2019-09-11 02:17 UTC, ShinjiShinozaki commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  set_param.frequency  = 523;
ドの音の周波数です。
勘違いでしたらすみません。

2019-09-11 02:17 UTC, ShinjiShinozaki commented on sdk/modules/audio/objects/synthesizer/synthesizer_obj.cpp
> +    }
Preの状態を設けます。

2019-09-11 08:30 UTC, ShinjiShinozaki-zz commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  set_param.frequency  = 523;
チャンネル別に少し周波数を変えました。

2019-09-11 08:43 UTC, ShinjiShinozaki commented
@TomonobuHayakawa さん
坂根さんの助けを借りまして、
スタートからストップまでのパスを通すことができました。
DSPの改造が必要ですが音がなりました。
参考
https://github.com/TomonobuHayakawa/spresense/pull/8
レビューよろしくお願いいたします。

2019-09-11 19:00 UTC, TomonobuHayakawa commented on examples/audio_oscillator/audio_oscillator_main.cxx
> +  set_param.frequency  = 523;
としたら、Beepで書いたように定義してほしいな。

2019-09-11 19:00 UTC, TomonobuHayakawa commented
一旦入れよう。

2019-09-11 19:00 UTC, merged